### ISSUE TITLE
Caching GraphQL queries including aliases

### ISSUE THREAD

**Issue by jakedoublev** [oslabs-beta/DenoStore#13]
Hi DenoStore team,
I think GraphQL aliases are not handled ideally in the current implementation. Data for aliased queries beyond the first one will be cached under the first query's alias and query name/args. However, follow-up queries for the data beyond that first query (though it's available in the cache) will not resolve in a cache hit because of how the cache key names are being generated. This is definitely fixable and will improve the tool utility.

GraphQL Aliases: https://graphql.org/learn/queries/#aliases

**Comment by lawauditswe** [comment]
Hey team,

In addition to the point Jake raised, it appears that given our current implementation, the same issue will also arise when caching fragments, operation names, and variables.

Relevant sections of GraphQL docs:
https://graphql.org/learn/queries/#fragments
https://graphql.org/learn/queries/#operation-name
https://graphql.org/learn/queries/#variables

**Comment by sktatsuno** [comment]
@jakedoublev @lawauditswe 
We are working on handling these GraphQL use cases

**Comment by Jamesmjkim** [comment]
#17 
We have a new approach that solves the problem with aliases and fragments.
